import { StyleSheet, Dimensions } from "react-native";
import { colors } from "../../assets/colors/colors";

const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8f9fa",
    },
    header: {
        paddingVertical: 15,
        backgroundColor: "white",
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 3,
    },
    title: {
        color: colors.primary,
        fontWeight: "bold",
        fontSize: 22,
        textAlign: "center",
    },
    underTitle: {
        color: "#666",
        fontSize: 14,
        textAlign: "center",
        marginTop: 3,
    },
    scrollContainer: {
        flex: 1,
    },
    calendar: {
        marginBottom: 10,
        borderRadius: 10,
        overflow: 'hidden',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    selectedDateContainer: {
        backgroundColor: '#f0f0f0',
        padding: 15,
        marginHorizontal: 10,
        marginVertical: 10,
        borderRadius: 10,
        alignItems: 'center',
    },
    selectedDateText: {
        fontSize: 18,
        fontWeight: '600',
        color: colors.primary,
    },
    eventsContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
        marginBottom: 10,
    },
    eventsList: {
        width: '100%',
        marginBottom: 10,
    },
    eventsListContent: {
        paddingHorizontal: 10,
    },
    emptyIcon: {
        marginBottom: 15,
        opacity: 0.7,
    },
    emptyTitle: {
        color: "#555",
        fontSize: 16,
        marginBottom: 25,
        textAlign: "center",
    },
    noteBox: {
        width: width * 0.9,
        alignSelf:"center",
        backgroundColor: "white",
        borderRadius: 15,
        padding: 15,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        marginBottom: 20
    },
    input: {
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 16,
        marginVertical: 10,
        paddingHorizontal: 16,
        paddingVertical: 12,
        fontSize: 12,
        backgroundColor: '#fafafa',
    },
    buttonBox: {
        backgroundColor: colors.primary,
        width: width * 0.4,
        alignSelf: "center",
        borderRadius: 24,
        marginTop: 10,
        marginBottom: 10,
        ...Platform.select({
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 2 },
                shadowOpacity: 0.2,
                shadowRadius: 3,
            },
            android: {
                elevation: 4,
            },
        }),
    },
    addButton: {
        textAlign: "center",
        padding: 14,
        color: "white",
        fontWeight: 'bold',
        fontSize: 16,
    },
    itemBox: {
        flexDirection: "row",
        alignItems: 'center',
        backgroundColor: 'white',
        marginVertical: 8,
        marginHorizontal: 16,
        padding: 16,
        borderRadius: 16,
        borderLeftWidth: 4,
        borderLeftColor: colors.primary,
        ...Platform.select({
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 2 },
                shadowOpacity: 0.1,
                shadowRadius: 3,
            },
            android: {
                elevation: 2,
            },
        }),
    },
    eventTitle: {
        flex: 1,
        fontWeight: "600",
        fontSize: 16,
        color: '#333',
    },
    icon: {
        padding: 8,
        backgroundColor: 'rgba(0, 0, 0, 0.05)',
        borderRadius: 20,
    },
    reminderIcon: {
        marginRight: 10,
    },
    reminderTime: {
        fontSize: 12,
        color: '#888',
        marginTop: 4,
    },
    notificationSwitch: {
        marginTop: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 8,
    },
    notificationText: {
        fontSize: 14,
        color: '#555',
    },
    timePickerButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f0f0f0',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 12,
        marginTop: 8,
    },
    timePickerText: {
        marginLeft: 6,
        color: '#555',
    },
    calendarTheme: {
        backgroundColor: '#ffffff',
        calendarBackground: '#ffffff',
        textSectionTitleColor: '#666',
        selectedDayBackgroundColor: colors.primary,
        selectedDayTextColor: '#ffffff',
        todayTextColor: colors.primary,
        dayTextColor: '#333',
        textDisabledColor: '#d9e1e8',
        dotColor: colors.primary,
        selectedDotColor: '#ffffff',
        arrowColor: colors.primary,
        monthTextColor: colors.primary,
        indicatorColor: colors.primary,
        textDayFontWeight: '400',
        textMonthFontWeight: 'bold',
        textDayHeaderFontWeight: '500',
        textDayFontSize: 16,
        textMonthFontSize: 16,
        textDayHeaderFontSize: 14,
    }
});